### PR TITLE
Master

### PR DESCRIPTION
**Pull request by c-tek**

### CODE REVIEW

**Comment by c-tek** [comment]
Release Candidate 1.
Complete with Download / Delete / Restore.
Backup rotate at 15 (hard coded into script)
Missing feature - User input for number of backups to keep instead of hard coded

**Comment by c-tek** [comment]
V1 ready to be packaged

**Comment by DavidePrincipi** [comment]
@c-tek, check the merge commit a058d0d. I think there are some unresolved conflicts that were commited. Please review them!

**Comment by c-tek** [comment]
I have resolved the conflicts (I hope that everything is ok)

**Comment by DavidePrincipi** [comment]
I reworked this PR avoiding modifications to the core library. The results are on this package:

http://packages.nethserver.org/nethserver/7.2.1511/nethforge-testing/x86_64/Packages/nethserver-backup-history-0.0.0-1.14.ga492b60.ns7.noarch.rpm

Sources are from [nethserver-backup-history](https://github.com/DavidePrincipi/nethserver-backup-history) repo.

**Pull request closed without merging**
